spring:
  datasource:
      url: jdbc:mysql://localhost:3306/javawebDB?serverTimezone=GMT&useSSL=false
      username: root
      password: 123456
mybatis:
   mapperLocations: classpath:/mapper/*.xml
server:
    port: 8080